/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/backup-adherence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GetBackupAdherence answers the question this product exists for: did every server's backup run
         *      when it was supposed to, and did it succeed. It compares each instance's declared expectation
         *      against the backups actually recorded, of either origin, and is computed on read — no verdict
         *      is stored, so there is nothing that can go stale.
         */
        get: operations["BackupService_GetBackupAdherence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backup-retention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description PreviewRetention reports what the next retention sweep would delete, and what it would refuse
         *      to delete and why. It is read-only and changes nothing.
         *
         *      It exists because retention is the only thing Fleetward does that destroys something, and an
         *      operator has to be able to see the answer before it is acted on rather than afterwards in a
         *      log. There is no job row per sweep to inspect (ADR-0030), so this is the surface that replaces
         *      one.
         */
        get: operations["BackupService_PreviewRetention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BackupService_ListBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{backup_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BackupService_GetBackup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backups/{backup_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description RunVerification restores a backup into an isolated sandbox and smoke-tests it. This is the
         *      product's defining operation.
         */
        post: operations["BackupService_RunVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InventoryService_ListEnvironments"];
        put?: never;
        post: operations["InventoryService_CreateEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SystemService_GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InventoryService_ListInstances"];
        put?: never;
        post: operations["InventoryService_CreateInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InventoryService_GetInstance"];
        put?: never;
        post?: never;
        delete: operations["InventoryService_DeleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BackupService_RunBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description DiscoverInstance refreshes topology, version, and database inventory for one instance. */
        post: operations["InventoryService_DiscoverInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/observe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description ObserveBackupHistory reads the engine's own record of backups Fleetward did not take and
         *      records what it finds (ADR-0015). It is the on-demand form of what an OBSERVE schedule does on
         *      a cadence, and it changes nothing on the instance it reads.
         */
        post: operations["BackupService_ObserveBackupHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/pitr-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BackupService_GetPITRWindow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/principals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InventoryService_ListPrincipalsForInstance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ScheduleService_CreateSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{instance_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description TestConnection resolves the stored credentials and performs a health check without persisting
         *      anything. Used by the add-instance wizard.
         */
        post: operations["InventoryService_TestConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ListJobs reports what the scheduler actually did. It is the only way to see that a run was
         *      skipped, leased by another replica, or closed by the reaper after a crash.
         */
        get: operations["ScheduleService_ListJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description ListPlugins reports every engine plugin the manager has loaded, with its capabilities. The UI
         *      uses this to decide which engines a user may add.
         */
        get: operations["SystemService_ListPlugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ScheduleService_ListSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ScheduleService_GetSchedule"];
        put?: never;
        post?: never;
        delete: operations["ScheduleService_DeleteSchedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{schedule_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description SetScheduleEnabled pauses or resumes a schedule without losing it. Pausing during a migration
         *      window is a normal operation, and deleting and recreating a schedule to achieve it would lose
         *      the history that points at it.
         */
        post: operations["ScheduleService_SetScheduleEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verifications/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BackupService_GetVerification"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SystemService_GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Backup: {
            id?: string;
            tenant_id?: string;
            instance_id?: string;
            method_id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "BACKUP_STATE_UNSPECIFIED" | "BACKUP_STATE_PENDING" | "BACKUP_STATE_RUNNING" | "BACKUP_STATE_SUCCEEDED" | "BACKUP_STATE_FAILED" | "BACKUP_STATE_CANCELED" | "BACKUP_STATE_EXPIRED" | "BACKUP_STATE_UNKNOWN";
            size_bytes?: string;
            checksum?: components["schemas"]["Checksum"];
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            duration?: string;
            /** Format: date-time */
            consistency_point?: string;
            /** Format: date-time */
            expires_at?: string;
            artifact?: components["schemas"]["ObjectRef"];
            error_message?: string;
            /** @description Most recent verification of this backup, if any. */
            verification?: components["schemas"]["Verification"];
            triggered_manually?: boolean;
            /**
             * Format: enum
             * @description Who took this backup. Managed backups carry a manifest Fleetward captured and can be verified;
             *      observed ones are evidence about somebody else's backup and cannot (ADR-0015). The two must
             *      never be rendered as the same green tick.
             * @enum {string}
             */
            origin?: "BACKUP_ORIGIN_UNSPECIFIED" | "BACKUP_ORIGIN_MANAGED" | "BACKUP_ORIGIN_OBSERVED";
            /** @description The identifier the engine gave this backup, where the engine assigns one. Empty otherwise. */
            external_id?: string;
            /**
             * @description Where the artifact is, as the engine names it. Set on observed backups, which Fleetward does
             *      not own; managed backups carry `artifact` instead.
             */
            external_location?: string;
            /** @description Only meaningful on an observed backup: what its evidence could and could not establish. */
            evidence?: components["schemas"]["ObservedEvidence"];
        };
        /**
         * @description BackupHistoryCapabilities declares what a plugin can observe of backups it did not take.
         *
         *      The fields are not decoration. Two engines' evidence differ in what they can actually prove: a
         *      history table the engine maintains records an outcome and an identity that survives anything; a
         *      directory listing records that a file exists. Presenting those as the same green tick is exactly
         *      the false confidence this product exists to eliminate, so what each source can and cannot support
         *      is declared here and core reports accordingly.
         */
        BackupHistoryCapabilities: {
            /** @description ListBackupHistory returns evidence rather than ERROR_CODE_UNSUPPORTED. */
            supported?: boolean;
            /**
             * @description Where the evidence comes from, in the engine's own vocabulary, so a report can say what it is
             *      reading. Display only — core must not branch on it.
             */
            source_description?: string;
            /**
             * @description ObservedBackup.external_id is an identifier the engine itself assigns, and therefore survives
             *      an artifact being moved or renamed. When false the plugin derives it from what it can see, so a
             *      renamed artifact may appear as a second backup, and Fleetward says so rather than double
             *      counting silently.
             */
            identity_is_engine_assigned?: boolean;
            /**
             * @description The evidence distinguishes a successful backup from a failed one. When false every record is
             *      OBSERVED_OUTCOME_UNKNOWN, and nothing downstream may render one as a success.
             */
            reports_outcome?: boolean;
            /**
             * @description Observation reads the directory of ADR-0026, so core refuses an observation schedule against an
             *      instance that has none — the same precondition BackupMethod.requires_shared_directory carries.
             */
            requires_shared_directory?: boolean;
        };
        BackupMethod: {
            /** @description Stable identifier referenced by BackupRequest.method_id, e.g. "pg_basebackup", "mysqldump". */
            id?: string;
            display_name?: string;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "BACKUP_KIND_UNSPECIFIED" | "BACKUP_KIND_PHYSICAL" | "BACKUP_KIND_LOGICAL" | "BACKUP_KIND_SNAPSHOT";
            /** @description Exactly one method per plugin should set this. */
            is_default?: boolean;
            /** @description Backups taken with this method can serve as a PITR baseline. */
            enables_pitr?: boolean;
            supports_incremental?: boolean;
            supports_compression?: boolean;
            supports_parallelism?: boolean;
            /** @description The instance must be offline or locked for the duration. Core warns loudly before scheduling. */
            requires_downtime?: boolean;
            required_tools?: string[];
            options?: components["schemas"]["MethodOption"][];
            /**
             * @description This method's tooling writes the artifact to the database server's own filesystem rather than
             *      to a stream, so it needs a directory the engine and the plugin can both reach (ADR-0026). Core
             *      refuses to schedule this method against an instance that has none, naming what is missing,
             *      rather than discovering it at 02:00.
             */
            requires_shared_directory?: boolean;
        };
        /**
         * @description BackupSummary is the two-part status the estate grid shows: did the backup succeed, and was it
         *      proven restorable. These are deliberately separate — a green backup with a red verification is
         *      the most dangerous state in the product and must never collapse into one indicator.
         *
         *      Deprecated: see Instance.backup_summary. Superseded by GetBackupAdherence.
         */
        BackupSummary: {
            /** Format: date-time */
            last_backup_at?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            last_backup_state?: "BACKUP_STATE_UNSPECIFIED" | "BACKUP_STATE_PENDING" | "BACKUP_STATE_RUNNING" | "BACKUP_STATE_SUCCEEDED" | "BACKUP_STATE_FAILED" | "BACKUP_STATE_CANCELED" | "BACKUP_STATE_EXPIRED" | "BACKUP_STATE_UNKNOWN";
            /** Format: date-time */
            last_verification_at?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            last_verification_status?: "VERIFICATION_STATUS_UNSPECIFIED" | "VERIFICATION_STATUS_VERIFIED" | "VERIFICATION_STATUS_FAILED" | "VERIFICATION_STATUS_INCONCLUSIVE";
            last_backup_id?: string;
        };
        /**
         * @description Capabilities is the typed feature matrix that core and the UI branch on. Declaring a capability
         *      the plugin does not actually implement is the one defect that will get a plugin rejected: core
         *      trusts this matrix when deciding what is safe to do to a production database.
         */
        Capabilities: {
            /**
             * @description Canonical engine identifier, e.g. "postgresql", "mysql", "mariadb", "mongodb", "redis".
             *      Used for display, sandbox image resolution, and grouping only — never for behavioral branching
             *      in core.
             */
            engine_type?: string;
            engine_display_name?: string;
            plugin_version?: string;
            /** @description Version of this contract the plugin was built against, e.g. "v1". */
            contract_version?: string;
            /** @description Engine versions this plugin is known to support, as semver ranges, e.g. ">=13 <17". */
            supported_engine_versions?: string[];
            /** @description Point-in-time recovery is available for instances of this engine. */
            supports_pitr?: boolean;
            /** @description The engine has a schema/database hierarchy worth discovering and displaying. */
            supports_schema_discovery?: boolean;
            /** @description GetConfig returns meaningful data. */
            supports_config_read?: boolean;
            /** @description The engine has a replication topology Discover can report. */
            supports_replication?: boolean;
            /**
             * @description Replication lag can be measured and is emitted as a metric. Core gates the lag health rule and
             *      the UI's lag column on this flag.
             */
            supports_replication_lag?: boolean;
            /** @description Storage utilization metrics are available, enabling the "storage > 85%" alert rule. */
            supports_storage_metrics?: boolean;
            /** @description At least one backup method runs without taking the instance offline. */
            supports_online_backup?: boolean;
            /**
             * @description Restore into a sandbox is possible. Automated backup verification requires this; without it
             *      core can back up but will report verification as unsupported rather than failed.
             */
            supports_sandbox_restore?: boolean;
            /** @description Restore can target a point in time, not just the artifact's own consistency point. */
            supports_point_in_time_restore?: boolean;
            backup_methods?: components["schemas"]["BackupMethod"][];
            /**
             * Format: enum
             * @enum {string}
             */
            principal_model?: "PRINCIPAL_MODEL_UNSPECIFIED" | "PRINCIPAL_MODEL_USERS" | "PRINCIPAL_MODEL_USERS_AND_ROLES" | "PRINCIPAL_MODEL_USERS_AND_GRANTS" | "PRINCIPAL_MODEL_ACL" | "PRINCIPAL_MODEL_NONE";
            /** @description Verification checks this plugin implements. Core requests a subset of these. */
            supported_verification_checks?: ("VERIFICATION_CHECK_UNSPECIFIED" | "VERIFICATION_CHECK_CONNECTIVITY" | "VERIFICATION_CHECK_RECORD_COUNTS" | "VERIFICATION_CHECK_SCHEMA_PRESENCE" | "VERIFICATION_CHECK_INTEGRITY" | "VERIFICATION_CHECK_QUERYABILITY")[];
            /** @description Metrics this plugin may emit, so core can register them without a collection round-trip. */
            metrics?: components["schemas"]["MetricDescriptor"][];
            /**
             * @description How to provision a sandbox for this engine. Core's SandboxProvider consumes this and stays
             *      engine-agnostic.
             */
            sandbox_template?: components["schemas"]["SandboxTemplate"];
            /**
             * @description External executables the plugin needs on its PATH, e.g. "pg_basebackup". Core surfaces missing
             *      tools as a plugin health problem rather than letting a backup fail at 3am.
             */
            required_tools?: string[];
            /**
             * @description What this plugin can see of backups Fleetward did not take (ADR-0015). Engines differ
             *      enormously, so this is a declaration rather than an assumption core may make.
             */
            backup_history?: components["schemas"]["BackupHistoryCapabilities"];
            /** @description Display-only metadata. Core must not branch on these. */
            metadata?: {
                [key: string]: string;
            };
        };
        CheckResult: {
            /**
             * Format: enum
             * @enum {string}
             */
            check?: "VERIFICATION_CHECK_UNSPECIFIED" | "VERIFICATION_CHECK_CONNECTIVITY" | "VERIFICATION_CHECK_RECORD_COUNTS" | "VERIFICATION_CHECK_SCHEMA_PRESENCE" | "VERIFICATION_CHECK_INTEGRITY" | "VERIFICATION_CHECK_QUERYABILITY";
            passed?: boolean;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_INFO" | "SEVERITY_WARNING" | "SEVERITY_CRITICAL";
            message?: string;
            discrepancies?: components["schemas"]["Discrepancy"][];
            duration?: string;
        };
        /** @description Checksum of an artifact, recorded at write time and re-verified before any restore. */
        Checksum: {
            /**
             * Format: enum
             * @enum {string}
             */
            algorithm?: "CHECKSUM_ALGORITHM_UNSPECIFIED" | "CHECKSUM_ALGORITHM_SHA256" | "CHECKSUM_ALGORITHM_CRC32C" | "CHECKSUM_ALGORITHM_BLAKE3";
            value?: string;
        };
        ComponentHealth: {
            /** @description Component name, e.g. "metadb", "tsdb", "objstore", "plugin:postgresql". */
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "SERVICE_HEALTH_UNSPECIFIED" | "SERVICE_HEALTH_HEALTHY" | "SERVICE_HEALTH_DEGRADED" | "SERVICE_HEALTH_UNHEALTHY";
            message?: string;
            latency?: string;
        };
        /**
         * @description ConnectionSpec carries credentials inbound only. No read API ever returns them: the secret is
         *      write-only from the API's perspective (ADR-0009).
         */
        ConnectionSpec: {
            username?: string;
            password?: string;
            database?: string;
            tls?: components["schemas"]["TLSSettings"];
            options?: {
                [key: string]: string;
            };
            /**
             * @description Where this instance's backup files are written, and where this control plane sees the same
             *      directory. Required only by an engine whose backup tooling produces a file on the database
             *      server rather than a stream, which the plugin declares on the method (ADR-0026). Fleetward
             *      refuses to back up such an instance without it, rather than discovering the gap at 02:00.
             */
            shared_directory?: components["schemas"]["SharedDirectory"];
        };
        CreateEnvironmentRequest: {
            name?: string;
            description?: string;
            is_production?: boolean;
        };
        CreateEnvironmentResponse: {
            environment?: components["schemas"]["Environment"];
        };
        CreateInstanceRequest: {
            environment_id?: string;
            name?: string;
            engine_type?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
            connection?: components["schemas"]["ConnectionSpec"];
            labels?: {
                [key: string]: string;
            };
        };
        CreateInstanceResponse: {
            instance?: components["schemas"]["Instance"];
        };
        CreateScheduleRequest: {
            instance_id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "JOB_KIND_UNSPECIFIED" | "JOB_KIND_BACKUP" | "JOB_KIND_VERIFY" | "JOB_KIND_RESTORE" | "JOB_KIND_DISCOVERY" | "JOB_KIND_METRICS" | "JOB_KIND_OBSERVE";
            cron_expression?: string;
            /** @description Defaults to UTC when empty. */
            timezone?: string;
            method_id?: string;
            options?: {
                [key: string]: string;
            };
            /**
             * Format: enum
             * @enum {string}
             */
            verify_policy?: "VERIFY_POLICY_UNSPECIFIED" | "VERIFY_POLICY_ALWAYS" | "VERIFY_POLICY_SAMPLED" | "VERIFY_POLICY_MANUAL";
            /** Format: int32 */
            verify_sample_percent?: number;
            /** Format: int32 */
            retention_days?: number;
            /**
             * @description See Schedule.expected_cron. Optional: a schedule with no expectation still collects history,
             *      and adherence reports that nothing was declared rather than guessing.
             */
            expected_cron?: string;
            /** Format: int32 */
            expected_grace_minutes?: number;
        };
        CreateScheduleResponse: {
            schedule?: components["schemas"]["Schedule"];
        };
        DatabaseInfo: {
            name?: string;
            size_bytes?: string;
            owner?: string;
            encoding?: string;
            collation?: string;
            /** @description Tables, collections, or the engine's nearest equivalent. */
            object_count?: string;
            /** @description System or internal database, which the UI de-emphasizes and backups usually skip. */
            is_system?: boolean;
        };
        DeleteInstanceResponse: Record<string, never>;
        DeleteScheduleResponse: Record<string, never>;
        DiscoverInstanceRequest: {
            instance_id?: string;
        };
        DiscoverInstanceResponse: {
            server?: components["schemas"]["ServerInfo"];
            databases?: components["schemas"]["DatabaseInfo"][];
            topology?: components["schemas"]["Topology"];
        };
        Discrepancy: {
            database?: string;
            object_name?: string;
            expected?: string;
            actual?: string;
            detail?: string;
        };
        Environment: {
            id?: string;
            tenant_id?: string;
            name?: string;
            description?: string;
            /** @description Marks production, which core uses to require stronger confirmation on destructive actions. */
            is_production?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        GetBackupAdherenceResponse: {
            instances?: components["schemas"]["InstanceAdherence"][];
        };
        GetBackupResponse: {
            backup?: components["schemas"]["Backup"];
            manifest?: components["schemas"]["SourceManifest"];
        };
        GetHealthResponse: {
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "SERVICE_HEALTH_UNSPECIFIED" | "SERVICE_HEALTH_HEALTHY" | "SERVICE_HEALTH_DEGRADED" | "SERVICE_HEALTH_UNHEALTHY";
            components?: components["schemas"]["ComponentHealth"][];
        };
        GetInstanceResponse: {
            instance?: components["schemas"]["Instance"];
            /**
             * @description Capabilities of the plugin serving this instance. The UI renders its tabs from this, which is
             *      how a capability-adaptive detail view stays engine-agnostic.
             */
            capabilities?: components["schemas"]["Capabilities"];
            server?: components["schemas"]["ServerInfo"];
            databases?: components["schemas"]["DatabaseInfo"][];
            topology?: components["schemas"]["Topology"];
        };
        GetPITRWindowResponse: {
            window?: components["schemas"]["PITRWindow"];
        };
        GetScheduleResponse: {
            schedule?: components["schemas"]["Schedule"];
        };
        GetVerificationResponse: {
            verification?: components["schemas"]["Verification"];
        };
        GetVersionResponse: {
            version?: string;
            commit?: string;
            build_date?: string;
            go_version?: string;
            contract_version?: string;
        };
        /** @description Contains an arbitrary serialized message along with a @type that describes the type of the serialized message. */
        GoogleProtobufAny: {
            /** @description The type of the serialized message. */
            "@type"?: string;
        } & {
            [key: string]: unknown;
        };
        HealthSignal: {
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            severity?: "SEVERITY_UNSPECIFIED" | "SEVERITY_INFO" | "SEVERITY_WARNING" | "SEVERITY_CRITICAL";
            message?: string;
            /** Format: double */
            value?: number;
            unit?: string;
        };
        HealthStatus: {
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "HEALTH_STATE_UNSPECIFIED" | "HEALTH_STATE_UP" | "HEALTH_STATE_DEGRADED" | "HEALTH_STATE_DOWN" | "HEALTH_STATE_UNKNOWN";
            message?: string;
            /** @description Round-trip latency of the health probe itself. */
            latency?: string;
            signals?: components["schemas"]["HealthSignal"][];
            engine_version?: string;
            /**
             * @description Set when the instance could not be reached. Accompanies HEALTH_STATE_DOWN rather than
             *      replacing it.
             */
            error?: components["schemas"]["PluginError"];
        };
        Instance: {
            id?: string;
            tenant_id?: string;
            environment_id?: string;
            name?: string;
            engine_type?: string;
            engine_version?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            health?: "HEALTH_STATE_UNSPECIFIED" | "HEALTH_STATE_UP" | "HEALTH_STATE_DEGRADED" | "HEALTH_STATE_DOWN" | "HEALTH_STATE_UNKNOWN";
            /** Format: date-time */
            last_seen_at?: string;
            labels?: {
                [key: string]: string;
            };
            /** Format: date-time */
            created_at?: string;
            /**
             * @description Deprecated: never populated. It was declared for an estate grid that did not exist yet, and by
             *      the time one did, GetBackupAdherence answered the same question better: it carries the verdict
             *      as well as the backup, and it reports an instance nobody has declared anything for, which this
             *      field cannot express. Read GetBackupAdherence instead. Removing this is a breaking change and
             *      leaving it silent was a lie, so it says so here.
             */
            backup_summary?: components["schemas"]["BackupSummary"];
        };
        /** @description InstanceAdherence is the gap between what was declared and what was detected, for one instance. */
        InstanceAdherence: {
            instance_id?: string;
            instance_name?: string;
            environment_id?: string;
            engine_type?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "ADHERENCE_STATE_UNSPECIFIED" | "ADHERENCE_STATE_ADHERENT" | "ADHERENCE_STATE_MISSED" | "ADHERENCE_STATE_UNPROVEN" | "ADHERENCE_STATE_FAILED" | "ADHERENCE_STATE_NOT_DECLARED";
            /** @description The declaration, echoed so a reader can see what they are being held to. */
            expected_cron?: string;
            timezone?: string;
            /** Format: int32 */
            expected_grace_minutes?: number;
            /**
             * Format: date-time
             * @description The most recent instant a backup was supposed to have happened by, and the deadline the grace
             *      period put on it.
             */
            expected_by?: string;
            /** Format: date-time */
            deadline?: string;
            /** @description The backup that satisfied the window, when one did. */
            satisfied_by?: components["schemas"]["Backup"];
            /**
             * @description The most recent backup of any kind, satisfying or not. Populated even when state is MISSED,
             *      because "the last one was nine days ago" is the useful part of a miss.
             */
            latest_backup?: components["schemas"]["Backup"];
            /**
             * @description What weakens this answer, in a sentence a human can act on: evidence that cannot report an
             *      outcome, an identity that will not survive a rename, a timestamp that may be out by an hour.
             *      Empty when the answer rests on nothing weaker than a backup Fleetward took itself.
             */
            caveats?: string[];
        };
        /**
         * @description Job is one unit of work the scheduler leases and runs. Every field after `state` exists to answer
         *      a question after the fact, which is the whole reason jobs are rows rather than goroutines.
         */
        Job: {
            id?: string;
            tenant_id?: string;
            instance_id?: string;
            /** @description Empty for a job a human triggered directly. */
            schedule_id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "JOB_KIND_UNSPECIFIED" | "JOB_KIND_BACKUP" | "JOB_KIND_VERIFY" | "JOB_KIND_RESTORE" | "JOB_KIND_DISCOVERY" | "JOB_KIND_METRICS" | "JOB_KIND_OBSERVE";
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "JOB_STATE_UNSPECIFIED" | "JOB_STATE_PENDING" | "JOB_STATE_RUNNING" | "JOB_STATE_SUCCEEDED" | "JOB_STATE_FAILED" | "JOB_STATE_CANCELED";
            /** Format: date-time */
            scheduled_for?: string;
            /**
             * @description Identifies the process holding the lease, as <hostname>/<pid>/<process-uuid>. The uuid is what
             *      keeps a restarted process on a recycled pid from looking like its own predecessor.
             */
            lease_owner?: string;
            /** Format: date-time */
            lease_expires_at?: string;
            /** Format: date-time */
            heartbeat_at?: string;
            /** Format: int32 */
            attempts?: number;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            error_message?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ListBackupsResponse: {
            backups?: components["schemas"]["Backup"][];
            next_page_token?: string;
            /** Format: int32 */
            total_size?: number;
        };
        ListEnvironmentsResponse: {
            environments?: components["schemas"]["Environment"][];
            next_page_token?: string;
        };
        ListInstancesResponse: {
            instances?: components["schemas"]["Instance"][];
            next_page_token?: string;
            /** Format: int32 */
            total_size?: number;
        };
        ListJobsResponse: {
            jobs?: components["schemas"]["Job"][];
        };
        ListPluginsResponse: {
            plugins?: components["schemas"]["PluginInfo"][];
        };
        ListPrincipalsForInstanceResponse: {
            principals?: components["schemas"]["Principal"][];
            /**
             * Format: enum
             * @enum {string}
             */
            model?: "PRINCIPAL_MODEL_UNSPECIFIED" | "PRINCIPAL_MODEL_USERS" | "PRINCIPAL_MODEL_USERS_AND_ROLES" | "PRINCIPAL_MODEL_USERS_AND_GRANTS" | "PRINCIPAL_MODEL_ACL" | "PRINCIPAL_MODEL_NONE";
        };
        ListSchedulesResponse: {
            schedules?: components["schemas"]["Schedule"][];
        };
        ManifestEntry: {
            database?: string;
            /** @description Table, collection, keyspace, or key pattern. */
            object_name?: string;
            /** @description Rows, documents, or keys. */
            record_count?: string;
            size_bytes?: string;
            /** @description Optional per-object content checksum, when the engine can produce one cheaply. */
            checksum?: string;
            /**
             * @description The count could not be pinned to the artifact's own consistency point, because the object was
             *      written to while the backup ran. A later mismatch is then drift rather than data loss, and is
             *      reported as INCONCLUSIVE rather than FAILED (ADR-0022). The default — false — means exact, so
             *      a manifest from a plugin that counts inside the snapshot it dumps keeps its meaning.
             */
            count_may_have_drifted?: boolean;
        };
        /**
         * @description MethodOption describes one tunable of a backup method so the UI can render a form without
         *      knowing anything about the engine.
         */
        MethodOption: {
            name?: string;
            display_name?: string;
            description?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            type?: "OPTION_TYPE_UNSPECIFIED" | "OPTION_TYPE_STRING" | "OPTION_TYPE_INT" | "OPTION_TYPE_BOOL" | "OPTION_TYPE_ENUM" | "OPTION_TYPE_DURATION";
            default_value?: string;
            required?: boolean;
            /** @description Populated when type is OPTION_TYPE_ENUM. */
            allowed_values?: string[];
        };
        MetricDescriptor: {
            /** @description OpenTelemetry semantic-convention name, e.g. "db.client.connection.count". */
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            type?: "METRIC_TYPE_UNSPECIFIED" | "METRIC_TYPE_GAUGE" | "METRIC_TYPE_SUM" | "METRIC_TYPE_UP_DOWN_COUNTER";
            /** @description UCUM unit, e.g. "1", "By", "s". */
            unit?: string;
            description?: string;
            /** @description Attribute keys this metric carries. */
            attribute_keys?: string[];
        };
        Node: {
            id?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
            /**
             * Format: enum
             * @enum {string}
             */
            role?: "NODE_ROLE_UNSPECIFIED" | "NODE_ROLE_PRIMARY" | "NODE_ROLE_REPLICA" | "NODE_ROLE_ARBITER" | "NODE_ROLE_ROUTER" | "NODE_ROLE_STANDALONE";
            state?: string;
            /**
             * Format: double
             * @description Populated only when Capabilities.supports_replication_lag is true.
             */
            replication_lag_seconds?: number;
            is_self?: boolean;
        };
        /**
         * @description ObjectRef locates an artifact in object storage. Plugins use it for identification and manifest
         *      bookkeeping; actual transfer happens through PresignedURL so that no storage credential ever
         *      reaches a plugin (ADR-0007).
         */
        ObjectRef: {
            bucket?: string;
            key?: string;
        };
        ObserveBackupHistoryRequest: {
            instance_id?: string;
        };
        ObserveBackupHistoryResponse: {
            /**
             * Format: int32
             * @description Records the engine reported that Fleetward had not already recorded.
             */
            discovered?: number;
            /**
             * Format: int32
             * @description Records that matched a backup already known, and updated it rather than duplicating it. A
             *      healthy estate settles at discovered = 0 and updated = a handful (ADR-0027).
             */
            updated?: number;
            /**
             * Format: date-time
             * @description The instant the newest evidence read in this poll finished at, which is where the next poll
             *      resumes from.
             */
            watermark?: string;
        };
        /**
         * @description ObservedEvidence is what the source this backup was read from could establish, carried alongside
         *      the backup so a reader is never left to assume. A directory listing proves a file arrived; it
         *      does not prove the dump that wrote it completed.
         */
        ObservedEvidence: {
            /** @description The source, in the engine's own vocabulary, e.g. "msdb.dbo.backupset". */
            source_description?: string;
            /** @description The source distinguishes success from failure. When false, `state` is UNKNOWN by construction. */
            reports_outcome?: boolean;
            /** @description The identity came from the engine, so a moved or renamed artifact stays one backup. */
            identity_is_engine_assigned?: boolean;
            /**
             * @description The finish time could not be converted to UTC with the offset in force on the day, so it may
             *      be out by a daylight-saving transition.
             */
            completed_at_is_approximate?: boolean;
            /** Format: date-time */
            observed_at?: string;
        };
        PITRBaseline: {
            backup_id?: string;
            /** Format: date-time */
            taken_at?: string;
            artifact?: components["schemas"]["ObjectRef"];
            method_id?: string;
        };
        PITRGap: {
            range?: components["schemas"]["TimeRange"];
            reason?: string;
        };
        PITRWindow: {
            /**
             * @description False when the engine or configuration does not currently support PITR — for example WAL
             *      archiving is off. The UI explains why using the reason field rather than showing an empty
             *      timeline.
             */
            available?: boolean;
            unavailable_reason?: string;
            /** Format: date-time */
            earliest?: string;
            /** Format: date-time */
            latest?: string;
            /** @description Periods inside [earliest, latest] that cannot actually be recovered to. */
            gaps?: components["schemas"]["PITRGap"][];
            baselines?: components["schemas"]["PITRBaseline"][];
            /** @description Smallest resolvable recovery interval. */
            granularity?: string;
        };
        /**
         * @description PasswordPolicy is what an engine will accept as a generated sandbox password.
         *
         *      Core generates the sandbox identity and the plugin's template places it (ADR-0020). Some images
         *      also validate it: mcr.microsoft.com/mssql/server exits rather than start when the password it is
         *      handed carries fewer than three of the four character classes. Declaring the rule lets core
         *      satisfy it by construction; leaving it empty keeps core's default generator unchanged.
         */
        PasswordPolicy: {
            /** Format: int32 */
            min_length?: number;
            /**
             * Format: int32
             * @description Minimum number of distinct classes — uppercase, lowercase, digit, symbol — that must appear.
             */
            min_character_classes?: number;
            /** @description Symbols this engine accepts, if its own set is narrower than core's. Empty keeps core's. */
            symbol_alphabet?: string;
        };
        /**
         * @description PluginError carries a structured failure from a plugin. Plugins should populate this rather than
         *      returning bare gRPC status strings, so core can classify retryable failures without parsing text.
         */
        PluginError: {
            /**
             * Format: enum
             * @enum {string}
             */
            code?: "ERROR_CODE_UNSPECIFIED" | "ERROR_CODE_CONNECTION_FAILED" | "ERROR_CODE_AUTHENTICATION_FAILED" | "ERROR_CODE_PERMISSION_DENIED" | "ERROR_CODE_UNSUPPORTED" | "ERROR_CODE_INVALID_ARGUMENT" | "ERROR_CODE_TOOL_NOT_FOUND" | "ERROR_CODE_TOOL_FAILED" | "ERROR_CODE_OBJECT_STORE_FAILED" | "ERROR_CODE_TIMEOUT" | "ERROR_CODE_CANCELED" | "ERROR_CODE_INTERNAL";
            /**
             * @description Human-readable message. MUST NOT contain credentials, connection strings with passwords, or
             *      presigned URL signatures.
             */
            message?: string;
            details?: {
                [key: string]: string;
            };
            /** @description True when core may usefully retry the same call. */
            retryable?: boolean;
        };
        PluginInfo: {
            engine_type?: string;
            capabilities?: components["schemas"]["Capabilities"];
            /**
             * Format: enum
             * @enum {string}
             */
            state?: "PLUGIN_STATE_UNSPECIFIED" | "PLUGIN_STATE_STARTING" | "PLUGIN_STATE_READY" | "PLUGIN_STATE_UNHEALTHY" | "PLUGIN_STATE_FAILED" | "PLUGIN_STATE_STOPPED";
            message?: string;
            /**
             * @description Tools declared as required that are missing on this host. A non-empty list means backups using
             *      the affected methods will fail, so core surfaces it before a schedule fires.
             */
            missing_tools?: string[];
            /** Format: int32 */
            restart_count?: number;
        };
        PreviewRetentionResponse: {
            /**
             * @description The limits the sweep runs under, echoed so that a surprising preview can be explained without
             *      reading the server's environment.
             */
            policy?: components["schemas"]["RetentionPolicy"];
            /** @description What the next sweep would expire and delete, oldest first, bounded by the sweep's own ceiling. */
            expiring?: components["schemas"]["RetentionCandidate"][];
            /**
             * @description Backups that are past their expiry and will not be deleted, each carrying the reason. This is
             *      the half of the answer that stops "why is that one still there" being a question only the
             *      source code answers.
             */
            protected?: components["schemas"]["RetentionCandidate"][];
            /**
             * @description Backups already marked expired whose artifact is still in object storage — the state a sweep
             *      interrupted between its two steps leaves behind. The next sweep finishes them (ADR-0030).
             */
            pending_deletion?: components["schemas"]["RetentionCandidate"][];
            /** @description How much object storage the next sweep would release. */
            reclaimable_bytes?: string;
        };
        Principal: {
            name?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "PRINCIPAL_KIND_UNSPECIFIED" | "PRINCIPAL_KIND_USER" | "PRINCIPAL_KIND_ROLE" | "PRINCIPAL_KIND_GROUP" | "PRINCIPAL_KIND_SERVICE";
            can_login?: boolean;
            /** @description Holds unrestricted or near-unrestricted rights. The UI flags these prominently. */
            is_superuser?: boolean;
            is_system?: boolean;
            /** @description Names of roles or groups this principal is a member of. */
            member_of?: string[];
            privileges?: components["schemas"]["Privilege"][];
            /** Format: date-time */
            password_expires_at?: string;
            /** Format: date-time */
            last_login_at?: string;
            attributes?: {
                [key: string]: string;
            };
        };
        Privilege: {
            /**
             * @description What the privilege applies to, as "type:identifier", e.g. "database:app",
             *      "table:public.users", "key:cache:*". Rendered as an opaque string by the UI.
             */
            scope?: string;
            /** @description The permitted action in the engine's own vocabulary, e.g. "SELECT", "readWrite", "+get". */
            action?: string;
            /** @description The principal may grant this privilege onward. */
            grantable?: boolean;
            granted_by?: string;
        };
        /** @description RetentionCandidate is one backup the sweep has an opinion about. */
        RetentionCandidate: {
            backup_id?: string;
            instance_id?: string;
            instance_name?: string;
            /** Format: date-time */
            completed_at?: string;
            /** Format: date-time */
            expires_at?: string;
            size_bytes?: string;
            /**
             * @description Why this backup will not be deleted, in a sentence a human can act on. Empty on a backup the
             *      sweep would remove.
             */
            protected_reason?: string;
        };
        /**
         * @description RetentionPolicy is the configured shape of the sweep, not a per-instance setting. Retention is an
         *      estate-wide property; what varies per backup is the expiry stamped on it (ADR-0031).
         */
        RetentionPolicy: {
            enabled?: boolean;
            interval?: string;
            /** Format: int32 */
            min_keep?: number;
            /** Format: int32 */
            max_per_sweep?: number;
        };
        RunBackupRequest: {
            instance_id?: string;
            /** @description Empty selects the plugin's default method. */
            method_id?: string;
            options?: {
                [key: string]: string;
            };
            databases?: string[];
            /** @description Run verification as soon as the backup completes, overriding the instance's policy. */
            verify_on_completion?: boolean;
        };
        RunBackupResponse: {
            backup_id?: string;
            job_id?: string;
        };
        RunVerificationRequest: {
            backup_id?: string;
            /** @description Checks to run. Empty runs every check the plugin supports. */
            checks?: ("VERIFICATION_CHECK_UNSPECIFIED" | "VERIFICATION_CHECK_CONNECTIVITY" | "VERIFICATION_CHECK_RECORD_COUNTS" | "VERIFICATION_CHECK_SCHEMA_PRESENCE" | "VERIFICATION_CHECK_INTEGRITY" | "VERIFICATION_CHECK_QUERYABILITY")[];
        };
        RunVerificationResponse: {
            verification_id?: string;
            job_id?: string;
        };
        /**
         * @description SandboxTemplate tells core how to stand up a throwaway instance of this engine for verification.
         *      Keeping it here — rather than in a core lookup table — is what allows a new engine to arrive as a
         *      plugin with no core change.
         */
        SandboxTemplate: {
            /** @description Image repository without a tag, e.g. "postgres". */
            image_repository?: string;
            /** @description Tag to use when the source instance's version cannot be matched, e.g. "16". */
            default_tag?: string;
            /**
             * @description Go text/template evaluated with the discovered engine version to produce a tag, e.g.
             *      "{{ .Major }}". Empty means always use default_tag.
             */
            tag_template?: string;
            env?: {
                [key: string]: string;
            };
            /** Format: int32 */
            container_port?: number;
            /** @description Command run inside the container to decide readiness, e.g. ["pg_isready", "-U", "postgres"]. */
            readiness_command?: string[];
            readiness_timeout?: string;
            command?: string[];
            /** @description Minimum tmpfs/volume size hint in bytes for the sandbox data directory. */
            min_disk_bytes?: string;
            /**
             * @description Path inside the container at which core mounts a directory the plugin can also read and write,
             *      for engines that hand their artifact over as a file (ADR-0026). Core reports both names for it
             *      in the sandbox's Credentials.shared_directory. Empty for engines that stream.
             */
            shared_directory?: string;
            /**
             * @description The administrative account this image always creates and cannot be told to rename, e.g. "sa".
             *      Core renders {{ .Username }} to it instead of generating a name, and still generates the
             *      password. Empty keeps the generated username, which is the behaviour ADR-0020 describes.
             */
            fixed_username?: string;
            /**
             * @description Complexity the image enforces on the password it is given. An image that refuses to start on a
             *      weak password fails in the worst possible way — rarely, and at provisioning time — so the
             *      policy is declared rather than discovered.
             */
            password_policy?: components["schemas"]["PasswordPolicy"];
        };
        /**
         * @description Schedule is a recurring intent. It is not a run: the scheduler materializes it into a Job when
         *      next_run_at falls due, and the job carries a snapshot of these parameters so that editing a
         *      schedule never rewrites what an in-flight run was asked to do.
         */
        Schedule: {
            id?: string;
            tenant_id?: string;
            instance_id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            kind?: "JOB_KIND_UNSPECIFIED" | "JOB_KIND_BACKUP" | "JOB_KIND_VERIFY" | "JOB_KIND_RESTORE" | "JOB_KIND_DISCOVERY" | "JOB_KIND_METRICS" | "JOB_KIND_OBSERVE";
            /** @description Standard five-field cron expression, interpreted in `timezone`. */
            cron_expression?: string;
            /**
             * @description IANA location name, e.g. "Europe/Bucharest". A DBA writing "0 2 * * *" means 02:00 where the
             *      server is, which is a different UTC instant in summer than in winter.
             */
            timezone?: string;
            /** @description Empty selects the plugin's default backup method. */
            method_id?: string;
            options?: {
                [key: string]: string;
            };
            /**
             * Format: enum
             * @enum {string}
             */
            verify_policy?: "VERIFY_POLICY_UNSPECIFIED" | "VERIFY_POLICY_ALWAYS" | "VERIFY_POLICY_SAMPLED" | "VERIFY_POLICY_MANUAL";
            /**
             * Format: int32
             * @description Only consulted when verify_policy is SAMPLED.
             */
            verify_sample_percent?: number;
            /** Format: int32 */
            retention_days?: number;
            /**
             * @description What a backup of this instance is supposed to look like, declared rather than inferred.
             *
             *      On an OBSERVE schedule `cron_expression` says how often to go and look; this says how often a
             *      backup is supposed to have happened, and how late is still acceptable. Inferring the second
             *      from the observed rhythm would answer "is this normal for you" instead of "is this what you
             *      asked for", and the second question is the product.
             */
            expected_cron?: string;
            /** Format: int32 */
            expected_grace_minutes?: number;
            is_enabled?: boolean;
            /**
             * Format: date-time
             * @description The clock. Always UTC on the wire and in storage, computed in `timezone`.
             */
            next_run_at?: string;
            /** Format: date-time */
            last_run_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ServerInfo: {
            engine_type?: string;
            /** @description Normalized semver where possible, e.g. "16.2". */
            version?: string;
            /** @description Raw version string as the engine reports it. */
            version_string?: string;
            uptime?: string;
            cluster_name?: string;
            data_directory?: string;
            read_only?: boolean;
            attributes?: {
                [key: string]: string;
            };
        };
        SetScheduleEnabledRequest: {
            schedule_id?: string;
            enabled?: boolean;
        };
        SetScheduleEnabledResponse: {
            schedule?: components["schemas"]["Schedule"];
        };
        /**
         * @description SharedDirectory is one directory under the two names its two users know it by.
         *
         *      An engine that answers BACKUP with a file rather than a stream writes it somewhere the plugin has
         *      no access to. The way out is a directory both sides can see — a mount, a share, or simply the
         *      local disk when the plugin runs on the database host — which the two of them almost never call by
         *      the same name. The plugin puts engine_path into the statements it sends and opens local_path
         *      itself; the bytes are the same bytes.
         */
        SharedDirectory: {
            /**
             * @description The path as the engine sees it. Used verbatim in statements sent to the engine, so it must be
             *      spelled the way that engine's platform spells a path.
             */
            engine_path?: string;
            /** @description The same directory as the process running the plugin sees it. */
            local_path?: string;
        };
        /** @description SourceManifest records what the source instance contained at backup time. */
        SourceManifest: {
            /** Format: date-time */
            captured_at?: string;
            entries?: components["schemas"]["ManifestEntry"][];
            total_objects?: string;
            total_records?: string;
            /** @description The plugin could only sample, so count comparisons are indicative rather than exact. */
            is_sampled?: boolean;
        };
        /** @description The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors). */
        Status: {
            /**
             * Format: int32
             * @description The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
             */
            code?: number;
            /** @description A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client. */
            message?: string;
            /** @description A list of messages that carry the error details.  There is a common set of message types for APIs to use. */
            details?: components["schemas"]["GoogleProtobufAny"][];
        };
        TLSSettings: {
            enabled?: boolean;
            /** @description Skips certificate verification. Intended for development only; core warns when it is set. */
            insecure_skip_verify?: boolean;
            /** Format: bytes */
            ca_pem?: string;
            /** Format: bytes */
            client_cert_pem?: string;
            /** Format: bytes */
            client_key_pem?: string;
            server_name?: string;
        };
        TestConnectionRequest: {
            instance_id?: string;
            /** @description Supply to test credentials that have not been stored yet, during the add-instance wizard. */
            connection?: components["schemas"]["ConnectionSpec"];
            engine_type?: string;
            host?: string;
            /** Format: int32 */
            port?: number;
        };
        TestConnectionResponse: {
            success?: boolean;
            health?: components["schemas"]["HealthStatus"];
            message?: string;
        };
        TimeRange: {
            /** Format: date-time */
            start?: string;
            /** Format: date-time */
            end?: string;
        };
        Topology: {
            nodes?: components["schemas"]["Node"][];
            /** @description The engine reports a topology but this instance is standalone. */
            is_standalone?: boolean;
        };
        Verification: {
            id?: string;
            backup_id?: string;
            /**
             * Format: enum
             * @enum {string}
             */
            status?: "VERIFICATION_STATUS_UNSPECIFIED" | "VERIFICATION_STATUS_VERIFIED" | "VERIFICATION_STATUS_FAILED" | "VERIFICATION_STATUS_INCONCLUSIVE";
            checks?: components["schemas"]["CheckResult"][];
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            completed_at?: string;
            duration?: string;
            report?: string;
            error_message?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BackupService_GetBackupAdherence: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to one instance or one environment. Both empty reports the whole estate, which is the
                 *      question a DBA with fifty servers actually asks.
                 */
                instance_id?: string;
                environment_id?: string;
                /** @description Report only instances that are not adherent. */
                problems_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBackupAdherenceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_PreviewRetention: {
        parameters: {
            query?: {
                /**
                 * @description Restrict to one instance. Empty previews the whole estate, which is the question an operator
                 *      about to enable retention actually asks.
                 */
                instance_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewRetentionResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_ListBackups: {
        parameters: {
            query?: {
                instance_id?: string;
                environment_id?: string;
                "within.start"?: string;
                "within.end"?: string;
                state?: "BACKUP_STATE_UNSPECIFIED" | "BACKUP_STATE_PENDING" | "BACKUP_STATE_RUNNING" | "BACKUP_STATE_SUCCEEDED" | "BACKUP_STATE_FAILED" | "BACKUP_STATE_CANCELED" | "BACKUP_STATE_EXPIRED" | "BACKUP_STATE_UNKNOWN";
                /**
                 * @description Return only backups whose latest verification failed. This is the query an on-call DBA runs
                 *      first, so it is a first-class filter rather than client-side work.
                 */
                verification_failed_only?: boolean;
                page_size?: number;
                page_token?: string;
                /**
                 * @description Restrict to backups of one origin. Unspecified returns both, which is what an adherence
                 *      question wants: it does not care who took the backup (ADR-0015).
                 */
                origin?: "BACKUP_ORIGIN_UNSPECIFIED" | "BACKUP_ORIGIN_MANAGED" | "BACKUP_ORIGIN_OBSERVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBackupsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_GetBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backup_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetBackupResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_RunVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backup_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunVerificationResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_ListEnvironments: {
        parameters: {
            query?: {
                page_size?: number;
                page_token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListEnvironmentsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_CreateEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvironmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateEnvironmentResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    SystemService_GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetHealthResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_ListInstances: {
        parameters: {
            query?: {
                environment_id?: string;
                /** @description Filter by engine. Display-level filtering only; core does not branch on this value. */
                engine_type?: string;
                page_size?: number;
                page_token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInstancesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_CreateInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateInstanceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_GetInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetInstanceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_DeleteInstance: {
        parameters: {
            query?: {
                /**
                 * @description Also delete backup artifacts belonging to this instance. Defaults to false: removing an
                 *      instance from the inventory must not silently destroy its backups.
                 */
                delete_artifacts?: boolean;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteInstanceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_RunBackup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunBackupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunBackupResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_DiscoverInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverInstanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverInstanceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_ObserveBackupHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObserveBackupHistoryRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObserveBackupHistoryResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_GetPITRWindow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPITRWindowResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_ListPrincipalsForInstance: {
        parameters: {
            query?: {
                include_privileges?: boolean;
                include_system?: boolean;
            };
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPrincipalsForInstanceResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_CreateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateScheduleResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    InventoryService_TestConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_ListJobs: {
        parameters: {
            query?: {
                instance_id?: string;
                schedule_id?: string;
                state?: "JOB_STATE_UNSPECIFIED" | "JOB_STATE_PENDING" | "JOB_STATE_RUNNING" | "JOB_STATE_SUCCEEDED" | "JOB_STATE_FAILED" | "JOB_STATE_CANCELED";
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListJobsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    SystemService_ListPlugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPluginsResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_ListSchedules: {
        parameters: {
            query?: {
                instance_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSchedulesResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_GetSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetScheduleResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_DeleteSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteScheduleResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    ScheduleService_SetScheduleEnabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetScheduleEnabledRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetScheduleEnabledResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    BackupService_GetVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVerificationResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    SystemService_GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetVersionResponse"];
                };
            };
            /** @description Default error response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
}
