package api

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"time"

	"github.com/danmorcov88/fleetward/internal/config"
	"github.com/danmorcov88/fleetward/internal/telemetry"
	"github.com/danmorcov88/fleetward/internal/version"
)

// Server is the control plane's HTTP surface: health endpoints, the REST API generated by
// grpc-gateway, and the OpenAPI document.
type Server struct {
	cfg    config.ServerConfig
	log    *slog.Logger
	health *Health
	mux    *http.ServeMux
	http   *http.Server
}

// NewServer builds the HTTP server.
func NewServer(cfg config.ServerConfig, log *slog.Logger, health *Health) (*Server, error) {
	mux := http.NewServeMux()

	s := &Server{
		cfg:    cfg,
		log:    log.With(slog.String("component", "http")),
		health: health,
		mux:    mux,
	}

	s.routes()

	tlsConfig, err := buildTLSConfig(cfg)
	if err != nil {
		return nil, err
	}

	s.http = &http.Server{
		Addr:         cfg.Addr,
		Handler:      s.middleware(mux),
		ReadTimeout:  cfg.ReadTimeout,
		WriteTimeout: cfg.WriteTimeout,
		IdleTimeout:  cfg.IdleTimeout,
		TLSConfig:    tlsConfig,
		ErrorLog:     slog.NewLogLogger(s.log.Handler(), slog.LevelWarn),
	}

	return s, nil
}

func (s *Server) routes() {
	s.mux.HandleFunc("GET /healthz", s.health.LivenessHandler())
	s.mux.HandleFunc("GET /readyz", s.health.ReadinessHandler())
	s.mux.HandleFunc("GET /api/v1/version", s.handleVersion)
}

// Mux exposes the router so later stages can mount the grpc-gateway handler and the OpenAPI
// document without this package having to know about them.
func (s *Server) Mux() *http.ServeMux { return s.mux }

func (s *Server) handleVersion(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, version.Get())
}

// Start listens and serves until the context is cancelled, then shuts down gracefully.
func (s *Server) Start(ctx context.Context) error {
	var lc net.ListenConfig
	listener, err := lc.Listen(ctx, "tcp", s.cfg.Addr)
	if err != nil {
		return fmt.Errorf("http: listen on %s: %w", s.cfg.Addr, err)
	}

	errCh := make(chan error, 1)
	go func() {
		s.log.Info("http server listening",
			slog.String("addr", listener.Addr().String()),
			slog.Bool("tls", s.cfg.TLSEnabled))

		var serveErr error
		if s.cfg.TLSEnabled {
			serveErr = s.http.ServeTLS(listener, s.cfg.TLSCertFile, s.cfg.TLSKeyFile)
		} else {
			serveErr = s.http.Serve(listener)
		}
		if serveErr != nil && !errors.Is(serveErr, http.ErrServerClosed) {
			errCh <- serveErr
			return
		}
		errCh <- nil
	}()

	select {
	case err := <-errCh:
		return err
	case <-ctx.Done():
		return s.Shutdown()
	}
}

// Shutdown stops the server, giving in-flight requests the configured grace period.
func (s *Server) Shutdown() error {
	timeout := s.cfg.ShutdownTimeout
	if timeout <= 0 {
		timeout = 20 * time.Second
	}
	// context.WithoutCancel because shutdown is normally triggered by a cancelled context, and
	// deriving the grace period from it would make the deadline expire immediately.
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	s.log.Info("http server shutting down", slog.Duration("grace_period", timeout))
	if err := s.http.Shutdown(ctx); err != nil {
		return fmt.Errorf("http: shutdown: %w", err)
	}
	return nil
}

// buildTLSConfig produces a modern TLS configuration, optionally requiring client certificates.
func buildTLSConfig(cfg config.ServerConfig) (*tls.Config, error) {
	if !cfg.TLSEnabled {
		return nil, nil
	}
	// Certificates are loaded by ServeTLS from the configured paths; this configuration fixes the
	// protocol floor so that enabling TLS cannot accidentally enable TLS 1.0.
	tlsCfg := &tls.Config{
		MinVersion: tls.VersionTLS12,
	}
	if cfg.TLSClientCAFile != "" {
		pool, err := loadCertPool(cfg.TLSClientCAFile)
		if err != nil {
			return nil, err
		}
		tlsCfg.ClientCAs = pool
		tlsCfg.ClientAuth = tls.RequireAndVerifyClientCert
	}
	return tlsCfg, nil
}

// middleware wraps the router with request identification, structured access logging, and panic
// recovery.
func (s *Server) middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		requestID := r.Header.Get("X-Request-Id")
		if requestID == "" {
			requestID = newRequestID()
		}
		w.Header().Set("X-Request-Id", requestID)

		ctx := telemetry.WithRequestID(r.Context(), requestID)
		r = r.WithContext(ctx)

		recorder := &statusRecorder{ResponseWriter: w, status: http.StatusOK}

		defer func() {
			if rec := recover(); rec != nil {
				s.log.ErrorContext(ctx, "panic serving request",
					slog.String("method", r.Method),
					slog.String("path", r.URL.Path),
					slog.Any("panic", rec))
				// A panic must never leak a stack trace to a client; the detail is in the log.
				if !recorder.wrote {
					writeProblem(w, http.StatusInternalServerError, "Internal Server Error",
						"An unexpected error occurred.", requestID)
				}
			}

			// Health probes fire constantly and would drown out everything else at info level.
			level := slog.LevelInfo
			if r.URL.Path == "/healthz" || r.URL.Path == "/readyz" {
				level = slog.LevelDebug
			}
			if recorder.status >= 500 {
				level = slog.LevelError
			}

			s.log.LogAttrs(ctx, level, "http request",
				slog.String("method", r.Method),
				slog.String("path", r.URL.Path),
				slog.Int("status", recorder.status),
				slog.Duration("duration", time.Since(start)),
				slog.String("remote_addr", clientIP(r)))
		}()

		next.ServeHTTP(recorder, r)
	})
}

type statusRecorder struct {
	http.ResponseWriter
	status int
	wrote  bool
}

func (r *statusRecorder) WriteHeader(code int) {
	if r.wrote {
		return
	}
	r.status = code
	r.wrote = true
	r.ResponseWriter.WriteHeader(code)
}

func (r *statusRecorder) Write(b []byte) (int, error) {
	r.wrote = true
	return r.ResponseWriter.Write(b)
}

// Problem is the single error shape every user-facing API error uses, following RFC 9457.
//
// One shape means a client can handle errors generically, and it means an error can never
// accidentally carry an internal detail that happens to be in scope at the call site.
type Problem struct {
	Type      string `json:"type"`
	Title     string `json:"title"`
	Status    int    `json:"status"`
	Detail    string `json:"detail,omitempty"`
	Instance  string `json:"instance,omitempty"`
	RequestID string `json:"request_id,omitempty"`
}

// WriteProblem sends a problem-details response.
func WriteProblem(w http.ResponseWriter, status int, title, detail, requestID string) {
	writeProblem(w, status, title, detail, requestID)
}

func writeProblem(w http.ResponseWriter, status int, title, detail, requestID string) {
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(Problem{
		Type:      "about:blank",
		Title:     title,
		Status:    status,
		Detail:    detail,
		RequestID: requestID,
	})
}

func clientIP(r *http.Request) string {
	host, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		return r.RemoteAddr
	}
	return host
}
