// Command docsgen writes the documentation that can be derived from the code.
//
// Some documentation is prose and belongs to a person. Some is a transcription of something the
// code already states exactly once — the environment variables the control plane reads, the tables
// the schema defines, the decisions on disk — and a transcription drifts. This project's
// configuration reference does not exist at all for that reason: writing sixty environment
// variables by hand and keeping them true was never going to happen.
//
// Generated output is committed, so a reader of the repository sees it without running anything,
// and CI regenerates and runs `git diff --exit-code`. That is the same idiom the protobuf codegen
// drift check already uses, rather than a second mechanism doing the same job differently.
//
// Usage:
//
//	docsgen [-C dir]
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// generator produces one file. Each is given the repository root and returns the complete content.
type generator struct {
	out  string // repository-relative path of the file to write
	what string
	run  func(root string) (string, error)
}

var generators = []generator{
	{"docs/ops/configuration.md", "the environment variables the control plane reads", genConfig},
	{"docs/dev/data-model.md", "the metadata schema, as entity diagrams", genSchema},
	{"docs/adr/README.md", "the decision-record index", genADRIndex},
}

// banner is prepended to every generated file. It names the source, because the first thing someone
// does on finding a mistake is try to edit the file in front of them.
func banner(source string) string {
	return fmt.Sprintf(`<!-- Generated by tools/docsgen. DO NOT EDIT. -->
<!-- Source: %s — change that, then run `+"`make docs`"+`. -->

`, source)
}

func main() {
	dir := flag.String("C", ".", "run as if docsgen had been started in `dir`")
	flag.Parse()

	root, err := filepath.Abs(*dir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "docsgen: %v\n", err)
		os.Exit(2)
	}

	for _, g := range generators {
		content, err := g.run(root)
		if err != nil {
			fmt.Fprintf(os.Stderr, "docsgen: %s: %v\n", g.out, err)
			os.Exit(1)
		}
		path := filepath.Join(root, filepath.FromSlash(g.out))
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			fmt.Fprintf(os.Stderr, "docsgen: %v\n", err)
			os.Exit(1)
		}
		// Written with LF regardless of platform: the file is committed, and a checkout on another
		// machine must not show the whole file as changed.
		if err := os.WriteFile(path, []byte(normalise(content)), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "docsgen: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("  wrote %-32s %s\n", g.out, g.what)
	}
}

func normalise(s string) string {
	s = strings.ReplaceAll(s, "\r\n", "\n")
	return strings.TrimRight(s, "\n") + "\n"
}

// table renders a markdown table, padding cells so the committed source is readable in a diff.
func table(headers []string, rows [][]string) string {
	widths := make([]int, len(headers))
	for i, h := range headers {
		widths[i] = len(h)
	}
	for _, r := range rows {
		for i, c := range r {
			if i < len(widths) && len(c) > widths[i] {
				widths[i] = len(c)
			}
		}
	}

	// The final column is left unpadded. It holds prose, and padding every row out to the widest
	// cell makes the committed source unreadable in a diff for no rendered benefit.
	last := len(headers) - 1

	var b strings.Builder
	writeRow := func(cells []string) {
		b.WriteString("|")
		for i, c := range cells {
			if i == last {
				fmt.Fprintf(&b, " %s |", c)
				continue
			}
			fmt.Fprintf(&b, " %-*s |", widths[i], c)
		}
		b.WriteString("\n")
	}
	writeRow(headers)
	b.WriteString("|")
	for i, w := range widths {
		if i == last {
			w = 3
		}
		b.WriteString(" " + strings.Repeat("-", max(w, 3)) + " |")
	}
	b.WriteString("\n")
	for _, r := range rows {
		writeRow(r)
	}
	return b.String()
}
